version: '3'

services:

    memcached:
        image: memcached:alpine
        container_name: memcached

    redis:
        image: redis:alpine
        container_name: redis

    web:
        image: nginx:latest
        container_name: web
        ports:
            - "8080:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        volumes:
            - ./www:/var/www/site
            - ./conf/nginx/site.template.conf:/etc/nginx/conf.d/site.template
        restart: always
        links:
            - php
            - mariadb

    php:
        build: .
        container_name: php
        volumes:
            - ./www:/var/www/site

    mariadb:
        image: 'bitnami/mariadb:latest'
        container_name: mariadb
        restart: always
        environment:
            - MARIADB_ROOT_USER=${MYSQL_ROOT_USER}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MARIADB_DATABASE=${MYSQL_DATABASE}
            - MARIADB_USER=${MYSQL_USER}
            - MARIADB_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - ./mysql:/bitnami

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mariadb

